// <auto-generated />
namespace LibraryFinalWinformProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ClassRoom : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClassRoom));
        
        string IMigrationMetadata.Id
        {
            get { return "202002131433289_ClassRoom"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
